pma:
  image: dnhsoft/phpmyadmin:4.6.4
  links:
   - db1
  ports:
   - "8001:80"
  environment:
   DBHOST: db1
   DBPASS: 3456789

db1:
  image: dnhsoft/mysql-utf8:5.7
  environment:
   MYSQL_ROOT_PASSWORD: 3456789
