pma:
  image: dnhsoft/phpmyadmin:latest
  links:
   - db1
  ports:
   - "8001:80"
  environment:
   DBHOST: db1
   DBUSER: admin
   DBPASS: 3456789

db1:
  image: tutum/mysql:5.6
  environment:
   MYSQL_PASS: 3456789
